# Generated by Django 5.1.7 on 2025-03-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('correo', models.CharField(max_length=90)),
                ('contraseña', models.CharField(max_length=20)),
                ('perfil_usuario', models.CharField(max_length=25)),
            ],
        ),
    ]
