# Generated by Django 5.1.7 on 2025-04-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('correo', models.CharField(max_length=90, unique=True)),
                ('contraseña', models.CharField(max_length=20)),
                ('perfil_usuario', models.BooleanField(default=False)),
                ('fecha_nacimiento', models.DateField()),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('tipo_documento', models.CharField(choices=[('CC', 'DNI'), ('CE', 'Pasaporte')], max_length=2)),
            ],
        ),
    ]
