# Generated by Django 5.1.7 on 2025-04-19 21:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pais', models.CharField(max_length=80)),
                ('codigo_pais', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('documento', models.CharField(max_length=45, unique=True)),
                ('contacto', models.CharField(max_length=25)),
                ('correo', models.EmailField(max_length=90, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=45)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_productos/')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=5, editable=False, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=5, editable=False, max_digits=10)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('pais_envio', models.CharField(max_length=45)),
                ('estado_orden', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado')], max_length=20)),
                ('numero_pedido', models.IntegerField(blank=True, null=True, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='compra.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura', models.DateTimeField(default=django.utils.timezone.now)),
                ('numero_factura', models.CharField(max_length=20, unique=True)),
                ('medio_pago', models.CharField(choices=[('tarjeta_credito', 'Tarjeta de Crédito'), ('tarjeta_debito', 'Tarjeta de Débito'), ('transferencia', 'Transferencia Bancaria'), ('paypal', 'PayPal')], max_length=25)),
                ('valor_total', models.DecimalField(decimal_places=5, max_digits=10)),
                ('nombre_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='compra.cliente')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='compra.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoHasProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('subtotal_producto', models.DecimalField(decimal_places=5, editable=False, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=5, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compra.pedido')),
            ],
        ),
    ]
