# Generated by Django 5.1.7 on 2025-03-30 20:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura', models.DateTimeField()),
                ('nombre_cliente', models.CharField(max_length=25)),
                ('descripcion_pedido', models.CharField(max_length=45)),
                ('medio_pago', models.CharField(max_length=25)),
                ('valor_total', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pais', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('documento_id', models.CharField(max_length=45)),
                ('contacto', models.CharField(max_length=25)),
                ('correo', models.EmailField(max_length=90)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=45)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compra.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=5, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=5, max_digits=10)),
                ('fecha_pedido', models.DateTimeField()),
                ('fecha_envio', models.DateTimeField()),
                ('pais_envio', models.CharField(max_length=45)),
                ('estado_orden', models.CharField(max_length=45)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.cliente')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='compra.factura')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura_relacionada', to='compra.pedido'),
        ),
        migrations.CreateModel(
            name='pedidoHasProductos', # name='PedidoHasProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compra.pedido')),
            ],
        ),
    ]
