# Generated by Django 5.1.7 on 2025-03-30 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('precio_unidad', models.DecimalField(decimal_places=5, max_digits=10)),
                ('cantidad_inventario', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('foto_producto', models.CharField(max_length=45)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.categoria')),
            ],
        ),
    ]
