# Generated by Django 5.1.7 on 2025-04-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_estilozapato_zapato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talla',
            name='numero',
        ),
        migrations.AddField(
            model_name='talla',
            name='valor',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='M', max_length=2),
            preserve_default=False,
        ),
    ]
