# Generated by Django 5.1.7 on 2025-04-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_talla_numero_talla_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talla',
            name='valor',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=4),
        ),
    ]
