# Generated by Django 5.1.7 on 2025-04-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_talla_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talla',
            name='valor',
            field=models.CharField(max_length=3),
        ),
    ]
