# Generated by Django 5.1.7 on 2025-04-20 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_talla_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estilozapato',
            name='categoria',
        ),
    ]
