# Generated by Django 5.1.7 on 2025-04-20 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_remove_estilozapato_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zapato',
        ),
    ]
