# Generated by Django 5.1.7 on 2025-03-30 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compra', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=25)),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores', to='compra.pais')),
                ('productos', models.ManyToManyField(related_name='proveedores', to='productos.producto')),
            ],
        ),
    ]
