# Generated by Django 5.1.7 on 2025-04-19 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='contacto',
        ),
    ]
